repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.0
    hooks:
        # Run the linter.
        - id: ruff
          args: [ --fix ]
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
