import { createRequire } from 'node:module';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const dir = process.env.ARTIFACT_DIR || '/tmp/receipt-review-artifacts';
await mkdir(dir, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH ?? (process.platform === 'darwin' ? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' : undefined), headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1050 }, httpCredentials: process.env.DEMO_PASSWORD ? {username:'demo',password:process.env.DEMO_PASSWORD} : undefined });
const report = { started: new Date().toISOString(), checks: [], errors: [] };
page.on('pageerror', error => report.errors.push(error.message));
const check = async (name, action) => { await action(); report.checks.push(name); };
const visible = async locator => { await locator.waitFor({ state: 'visible' }); };
try {
  // A synthetic receipt is the fixture, never a user's document.
  await page.setContent(`<body style="margin:0;background:white;width:380px;font:18px monospace;color:#333"><div style="padding:40px"><h2 style="text-align:center">NORTHSIDE COFFEE</h2><p style="text-align:center">21 Market Street<br>New York, NY</p><hr><p>Receipt: <span id="invoice-number-token">INV-1042</span></p><p>30 Sep 2026 · 09:41</p><hr><p>Flat white     $4.50</p><p>Croissant      $3.75</p><br><hr><p>TOTAL          $8.25</p><br><p style="text-align:center">Thank you. See you soon!</p></div></body>`);
  const invoiceBox = await page.locator('#invoice-number-token').evaluate(el => { const token = el.getBoundingClientRect(); const body = document.body.getBoundingClientRect(); const scale = (value, origin, extent) => Math.round((value - origin) * 1000 / extent); return [scale(token.left, body.left, body.width), scale(token.top, body.top, body.height), scale(token.right, body.left, body.width), scale(token.bottom, body.top, body.height)]; });
  const bodySize = await page.locator('body').evaluate(el => { const rect = el.getBoundingClientRect(); return {width: rect.width, height: rect.height}; });
  const receipt = await page.locator('body').screenshot();
  const jpeg = await page.locator('body').screenshot({type:'jpeg'});
  const tiff = Buffer.from([0x49,0x49,0x2a,0,8,0,0,0,1,0,0x12,0x01,0x03,0,1,0,0,0,6,0,0,0,0,0,0,0]);
  const exif = Buffer.concat([Buffer.from('Exif\0\0'),tiff]);
  const app1 = Buffer.alloc(4);app1.writeUInt16BE(0xffe1,0);app1.writeUInt16BE(exif.length+2,2);
  const rotatedImage = {name:'receipt-rotated.jpg',mimeType:'image/jpeg',buffer:Buffer.concat([jpeg.subarray(0,2),app1,exif,jpeg.subarray(2)])};
  const image = { name: 'receipt.png', mimeType: 'image/png', buffer: receipt };
  const ocr = { name: 'receipt.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({words:['INV-1042'],bboxes:[invoiceBox]})) };
  let status = 200, raw = null;
  let data = { invoice_number: 'INV-1042', extraction_method: 'heuristic', total_words: 1, predictions: [{word:'INV-1042',label:'HEURISTIC_MATCH',is_invoice_number:true}] };
  await page.route('**/api/predict', async route => {
    await new Promise(resolve => setTimeout(resolve, 180));
    await route.fulfill({status, contentType:raw ? 'text/plain' : 'application/json',body:raw || JSON.stringify(data)});
  });
  await page.goto(process.env.BASE_URL || 'http://localhost:3100');
  const extract = page.getByRole('button', {name:'Extract invoice number'});
  await check('Empty state; extraction requires an image', async()=>{ await visible(page.getByText('No data extracted')); assert(await extract.isDisabled()); });
  await page.screenshot({path:`${dir}/desktop-empty.png`,fullPage:true});
  await check('Unsupported image gives actionable error', async()=>{await page.getByLabel('Receipt image',{exact:true}).setInputFiles({name:'receipt.pdf',mimeType:'application/pdf',buffer:Buffer.from('pdf')}); await visible(page.locator('.error-message'));});
  await check('Image preview enables extraction; valid OCR can be added', async()=>{await page.getByLabel('Receipt image',{exact:true}).setInputFiles(image); await visible(page.getByAltText('Your uploaded receipt')); assert(await extract.isEnabled()); await page.locator('#ocr-file').setInputFiles(ocr); assert(await extract.isEnabled()); });
  await check('Loading, successful extraction, and needs review',async()=>{await extract.click();await visible(page.getByText('Extracting invoice number…'));await visible(page.getByText('Needs review',{exact:true}));assert.equal(await page.locator('#invoice-number').inputValue(),'INV-1042');});
  await check('Invoice number coordinates render a red box on the source',async()=>{const rect=page.locator('.detection-overlay rect').first();await visible(rect);assert.equal(await page.locator('.detection-overlay rect').count(),1);assert.equal(Number(await rect.getAttribute('x')),invoiceBox[0]);assert.equal(Number(await rect.getAttribute('y')),invoiceBox[1]);await visible(page.locator('.match-legend'));});
  await check('TXT OCR splits invoice tokens and normalizes pixel coordinates',async()=>{const coords=[invoiceBox[0]*bodySize.width/1000,invoiceBox[1]*bodySize.height/1000,invoiceBox[2]*bodySize.width/1000,invoiceBox[1]*bodySize.height/1000,invoiceBox[2]*bodySize.width/1000,invoiceBox[3]*bodySize.height/1000,invoiceBox[0]*bodySize.width/1000,invoiceBox[3]*bodySize.height/1000].map(Math.round);await page.locator('#ocr-file').setInputFiles({name:'receipt.txt',mimeType:'text/plain',buffer:Buffer.from(`${coords.join(',')},INV-1042\n`)});data={invoice_number:'INV-1042',extraction_method:'heuristic',total_words:3,predictions:[{word:'INV',label:'LABEL_1',is_invoice_number:true},{word:'-',label:'LABEL_0',is_invoice_number:false},{word:'1042',label:'LABEL_2',is_invoice_number:true}]};await extract.click();await visible(page.getByText('Needs review',{exact:true}));await visible(page.locator('.detection-overlay rect').first());assert.equal(await page.locator('.detection-overlay rect').count(),2);});
  await check('Zoom stays scrollable at the top-left image edges',async()=>{await page.getByRole('button',{name:'Zoom',exact:true}).click();const preview=page.locator('.receipt-preview');const edges=await page.evaluate(()=>{const preview=document.querySelector('.receipt-preview').getBoundingClientRect();const frame=document.querySelector('.receipt-image-frame').getBoundingClientRect();return {left:frame.left-preview.left,top:frame.top-preview.top};});assert(edges.left>=15);assert(edges.top>=15);await preview.evaluate(el=>{el.scrollLeft=el.scrollWidth;el.scrollTop=el.scrollHeight;});const end=await preview.evaluate(el=>({left:el.scrollLeft,top:el.scrollTop}));assert(end.left>0);assert(end.top>0);await preview.evaluate(el=>{el.scrollLeft=0;el.scrollTop=0;});await page.getByRole('button',{name:'Fit',exact:true}).click();});
  await check('JPEG EXIF rotation transforms the box to the displayed orientation',async()=>{await page.getByRole('button',{name:'Start over'}).click();await page.getByLabel('Receipt image',{exact:true}).setInputFiles(rotatedImage);await page.locator('#ocr-file').setInputFiles(ocr);data={invoice_number:'INV-1042',extraction_method:'heuristic',total_words:1,predictions:[{word:'INV-1042',label:'HEURISTIC_MATCH',is_invoice_number:true}]};await extract.click();await visible(page.getByText('Needs review',{exact:true}));const rect=page.locator('.detection-overlay rect').first();await visible(rect);assert.equal(await page.locator('.detection-overlay rect').count(),1);assert.equal(Number(await rect.getAttribute('x')),1000-invoiceBox[3]);assert.equal(Number(await rect.getAttribute('y')),invoiceBox[0]);assert.equal(Number(await rect.getAttribute('width')),invoiceBox[3]-invoiceBox[1]);assert.equal(Number(await rect.getAttribute('height')),invoiceBox[2]-invoiceBox[0]);});
  await page.screenshot({path:`${dir}/desktop-result.png`,fullPage:true});
  await check('Review is explicit; editing clears review',async()=>{await page.getByRole('button',{name:'Confirm number',exact:true}).click();await visible(page.getByText('Reviewed',{exact:true}));await page.locator('#invoice-number').fill('INV-1043');await visible(page.getByText('Needs review',{exact:true}));await visible(page.getByText('Originally extracted:'));});
  await check('Copy uses corrected number',async()=>{await page.context().grantPermissions(['clipboard-read','clipboard-write']);await page.getByRole('button',{name:'Copy number'}).click();await visible(page.getByText('Copied to clipboard'));assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'INV-1043');});
  await check('Extraction details contain matched tokens',async()=>{await page.getByText('Extraction details',{exact:false}).click();await visible(page.locator('.word-list .matched').first());});
  await check('Mobile result has no horizontal overflow',async()=>{await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`${dir}/mobile-result.png`,fullPage:true});});
  await check('Changing OCR clears stale results',async()=>{await page.locator('#ocr-file').setInputFiles(ocr);await visible(page.getByText('No data extracted'));});
  data={...data,invoice_number:'Not Found',predictions:[]};
  await check('No match requires manual correction',async()=>{await extract.click();await visible(page.getByText('We couldn’t find an invoice number.'));assert(await page.getByRole('button',{name:'Confirm number',exact:true}).isDisabled());await page.locator('#invoice-number').fill('MANUAL-1');await page.getByRole('button',{name:'Confirm number',exact:true}).click();await visible(page.getByText('Reviewed',{exact:true}));});
  data={...data,invoice_number:'INV 1042',predictions:[{word:'INV',label:'LABEL_1',is_invoice_number:true},{word:'1042',label:'LABEL_2',is_invoice_number:true}]};
  await check('Multiple matches prompt careful review',async()=>{await extract.click();await visible(page.getByText('More than one word was matched.',{exact:false}));});
  status=502;raw='Bad gateway';
  await check('Non-JSON server errors remain retryable',async()=>{await extract.click();await visible(page.locator('.error-message'));assert(await extract.isEnabled());});
  status=200;raw=null;data={invoice_number:'bad'};
  await check('Malformed responses do not show success',async()=>{await extract.click();await visible(page.getByText('We received an incomplete result. Please try again.'));});
  await check('Oversized OCR falls back to image-only inference',async()=>{data={invoice_number:'INV-1042',extraction_method:'openrouter_image_only',total_words:0,predictions:[]};await page.locator('#ocr-file').setInputFiles({name:'large.json',mimeType:'application/json',buffer:Buffer.alloc(2_000_001)});await extract.click();await visible(page.getByText('Needs review',{exact:true}));await visible(page.getByText('Image only',{exact:true}));});
  await check('Reset clears image, files, and result',async()=>{await page.getByRole('button',{name:'Start over'}).click();await visible(page.getByText('Upload document'));assert(await extract.isDisabled());});
  await check('Unreadable image is rejected',async()=>{await page.getByLabel('Receipt image',{exact:true}).setInputFiles({name:'corrupt.png',mimeType:'image/png',buffer:Buffer.from('invalid')});await visible(page.getByText('This image could not be opened.',{exact:false}));});
  await check('Real API rejects missing files without inference',async()=>{const response=await page.request.post(`${process.env.BASE_URL || 'http://localhost:3100'}/api/predict`,{multipart:{}});assert.equal(response.status(),400);});
  await check('Real API validates unsupported uploads',async()=>{const response=await page.request.post(`${process.env.BASE_URL || 'http://localhost:3100'}/api/predict`,{multipart:{image:{name:'receipt.pdf',mimeType:'application/pdf',buffer:Buffer.from('fake')},ocr_file:ocr}});assert.equal(response.status(),400);});
  assert.deepEqual(report.errors,[]);
  report.status='passed';
} catch(error) { report.status='failed';report.failure=String(error.stack);await page.screenshot({path:`${dir}/failure.png`,fullPage:true});process.exitCode=1; }
finally {report.finished=new Date().toISOString();await writeFile(`${dir}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
